# Generated by Django 2.2.1 on 2022-01-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_attendencevideofileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceCSVFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTeacher', models.CharField(max_length=255)),
                ('semester_csv', models.CharField(max_length=255)),
                ('year_csv', models.CharField(max_length=255)),
                ('subject_csv', models.CharField(max_length=255)),
                ('timing_csv', models.CharField(max_length=255)),
                ('csvfile', models.FileField(upload_to='')),
            ],
        ),
    ]
